kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kyverno-config
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template: 
    metadata:
      name: 'cluster-{{name}}-config'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: "default"
      sources:
      - repoURL: https://github.com/nirmata/demo-namespaces-as-a-service
        targetRevision: HEAD
        path: config/shared-cluster/roles/
      destination:
        server: '{{server}}'
      syncPolicy:
        syncOptions:
        - Replace=true
        automated:
          selfHeal: true
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s