kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'cluster-{{name}}-policies'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: "default"
      sources:
      - repoURL: https://github.com/nsagark/mystuff.git
        targetRevision: tnt2
        path: mypolicies/
      destination:
        server: '{{server}}'
      syncPolicy:
        syncOptions:
        - Replace=true
        automated:
          selfHeal: true
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
