---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-ns-access-controls
  annotations:
    policies.kyverno.io/description: >-
      Generate Roles and RoleBindings for namespace owners
spec:
  background: false
  rules:
    - name: generate-owner-role
      match:
        resources:
          kinds:
            - Namespace
          operations:
            - CREATE
      exclude:
        clusterRoles:
          - "cluster-admin"
      generate:
        synchronize: true
        kind: ClusterRole
        apiVersion: rbac.authorization.k8s.io/v1
        name: "ns-admin-{{request.object.metadata.name}}-{{request.object.metadata.labels.owner}}"
        data:
          metadata:
            annotations:
              kyverno.io/user: "{{request.object.metadata.labels.owner}}"
          rules:
            - apiGroups: [""]
              resources: ["namespaces"]
              verbs: ["get", "delete"]
              resourceNames:
                - "{{request.object.metadata.name}}"
    - name: generate-owner-role-binding
      match:
        resources:
          kinds:
            - Namespace
          operations:
            - CREATE    
      exclude:
        clusterRoles:
          - "cluster-admin"
      generate:
        synchronize: true
        kind: ClusterRoleBinding
        apiVersion: rbac.authorization.k8s.io/v1
        name: "ns-admin-{{request.object.metadata.name}}-{{request.object.metadata.labels.owner}}-binding"
        data:
          metadata:
            annotations:
              kyverno.io/user: "{{request.object.metadata.labels.owner}}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: "ns-admin-{{request.object.metadata.name}}-{{request.object.metadata.labels.owner}}"
          subjects:
            - kind: User
              name: "{{request.object.metadata.labels.owner}}"
    - name: generate-admin-binding
      match:
        resources:
          kinds:
            - Namespace
          operations:
            - CREATE
      exclude:
        clusterRoles:
          - "cluster-admin"
      generate:
        synchronize: true
        kind: RoleBinding
        apiVersion: rbac.authorization.k8s.io/v1
        name: "{{request.object.metadata.labels.owner}}-admin-binding"
        namespace: "{{request.object.metadata.name}}"
        data:
          metadata:
            annotations:
              kyverno.io/user: "{{request.object.metadata.labels.owner}}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
          subjects:
            - kind: User
              name: "{{request.object.metadata.labels.owner}}"